### ISSUE TITLE
[BUG] Dosent load

### ISSUE THREAD

**Issue by UltimateBoi** [logicguy1/Discord-Nitro-Generator-and-Checker#79]
Basically when i try to run it loads then after it types "Enter the amount" etc, it comes up with this error:

`Traceback (most recent call last):
  File "C:\Users\Ultimate\Downloads\Discord-Nitro-Generator-and-Checker-main\Discord-Nitro-Generator-and-Checker-main\main.py", line 182, in <module>
    Gen.main() # Run the main code
  File "C:\Users\Ultimate\Downloads\Discord-Nitro-Generator-and-Checker-main\Discord-Nitro-Generator-and-Checker-main\main.py", line 59, in main
    num = int(input('')) # Ask the user for the amount of codes
ValueError: invalid literal for int() with base 10: ''`

**Comment by sys-256** [comment]
It basically says that what you entered is not an integer. Are you sure your entered value only exists out of numbers (so no spaces, periods, and commas)?

**Comment by soshimee** [comment]
For me it happens even though I didn't enter ANYTHING.

**Comment by logicguy1** [comment]
Nothing is NaN

**Comment by lukehodges** [comment]
You need to enter an number otherwise it cannot convert a string to a base10
